// Curated list of major US cities (city → state) used by the location
// autocomplete. Kept deliberately to the largest metro areas so suggestions
// stay useful without shipping a huge dataset. When a city is selected the
// location form auto-fills its state into the region field.
export const US_CITIES = [
  { city: "New York", state: "NY" },
  { city: "Los Angeles", state: "CA" },
  { city: "Chicago", state: "IL" },
  { city: "Houston", state: "TX" },
  { city: "Phoenix", state: "AZ" },
  { city: "Philadelphia", state: "PA" },
  { city: "San Antonio", state: "TX" },
  { city: "San Diego", state: "CA" },
  { city: "Dallas", state: "TX" },
  { city: "San Jose", state: "CA" },
  { city: "Austin", state: "TX" },
  { city: "Jacksonville", state: "FL" },
  { city: "Fort Worth", state: "TX" },
  { city: "Columbus", state: "OH" },
  { city: "Indianapolis", state: "IN" },
  { city: "Charlotte", state: "NC" },
  { city: "San Francisco", state: "CA" },
  { city: "Seattle", state: "WA" },
  { city: "Denver", state: "CO" },
  { city: "Washington", state: "DC" },
  { city: "Nashville", state: "TN" },
  { city: "Oklahoma City", state: "OK" },
  { city: "El Paso", state: "TX" },
  { city: "Boston", state: "MA" },
  { city: "Portland", state: "OR" },
  { city: "Las Vegas", state: "NV" },
  { city: "Detroit", state: "MI" },
  { city: "Memphis", state: "TN" },
  { city: "Louisville", state: "KY" },
  { city: "Baltimore", state: "MD" },
  { city: "Milwaukee", state: "WI" },
  { city: "Albuquerque", state: "NM" },
  { city: "Tucson", state: "AZ" },
  { city: "Fresno", state: "CA" },
  { city: "Sacramento", state: "CA" },
  { city: "Mesa", state: "AZ" },
  { city: "Kansas City", state: "MO" },
  { city: "Atlanta", state: "GA" },
  { city: "Omaha", state: "NE" },
  { city: "Colorado Springs", state: "CO" },
  { city: "Raleigh", state: "NC" },
  { city: "Miami", state: "FL" },
  { city: "Virginia Beach", state: "VA" },
  { city: "Long Beach", state: "CA" },
  { city: "Oakland", state: "CA" },
  { city: "Minneapolis", state: "MN" },
  { city: "Tampa", state: "FL" },
  { city: "Tulsa", state: "OK" },
  { city: "Arlington", state: "TX" },
  { city: "New Orleans", state: "LA" },
  { city: "Wichita", state: "KS" },
  { city: "Cleveland", state: "OH" },
  { city: "Bakersfield", state: "CA" },
  { city: "Anaheim", state: "CA" },
  { city: "Honolulu", state: "HI" },
  { city: "Henderson", state: "NV" },
  { city: "Orlando", state: "FL" },
  { city: "Santa Ana", state: "CA" },
  { city: "Cincinnati", state: "OH" },
  { city: "St. Louis", state: "MO" },
  { city: "Pittsburgh", state: "PA" },
  { city: "Greensboro", state: "NC" },
  { city: "Lexington", state: "KY" },
  { city: "Anchorage", state: "AK" },
  { city: "Plano", state: "TX" },
  { city: "Newark", state: "NJ" },
  { city: "Buffalo", state: "NY" },
  { city: "Henderson", state: "NV" },
  { city: "Lincoln", state: "NE" },
  { city: "Fort Wayne", state: "IN" },
  { city: "Jersey City", state: "NJ" },
  { city: "Chandler", state: "AZ" },
  { city: "St. Petersburg", state: "FL" },
  { city: "Laredo", state: "TX" },
  { city: "Madison", state: "WI" },
  { city: "Durham", state: "NC" },
  { city: "Lubbock", state: "TX" },
  { city: "Winston-Salem", state: "NC" },
  { city: "Garland", state: "TX" },
  { city: "Glendale", state: "AZ" },
  { city: "Hialeah", state: "FL" },
  { city: "Reno", state: "NV" },
  { city: "Chesapeake", state: "VA" },
  { city: "Gilbert", state: "AZ" },
  { city: "Baton Rouge", state: "LA" },
  { city: "Irvine", state: "CA" },
  { city: "Akron", state: "OH" },
  { city: "Birmingham", state: "AL" },
  { city: "Stockton", state: "CA" },
  { city: "Richmond", state: "VA" },
  { city: "Corpus Christi", state: "TX" },
  { city: "Fremont", state: "CA" },
  { city: "Scottsdale", state: "AZ" },
  { city: "Rochester", state: "NY" },
  { city: "Sioux Falls", state: "SD" },
  { city: "Spokane", state: "WA" },
  { city: "Boise", state: "ID" },
  { city: "Modesto", state: "CA" },
  { city: "Oxnard", state: "CA" },
  { city: "Tacoma", state: "WA" },
  { city: "Fontana", state: "CA" },
  { city: "Fayetteville", state: "NC" },
  { city: "Moreno Valley", state: "CA" },
  { city: "Yonkers", state: "NY" },
  { city: "Huntington Beach", state: "CA" },
  { city: "Salt Lake City", state: "UT" },
  { city: "Grand Rapids", state: "MI" },
  { city: "Aurora", state: "CO" },
  { city: "Des Moines", state: "IA" },
  { city: "Providence", state: "RI" },
  { city: "Knoxville", state: "TN" },
  { city: "Bakersfield", state: "CA" },
  { city: "Pasadena", state: "TX" },
  { city: "Brownsville", state: "TX" },
  { city: "Santa Clarita", state: "CA" },
  { city: "McKinney", state: "TX" },
  { city: "Amarillo", state: "TX" },
  { city: "Overland Park", state: "KS" },
  { city: "Grand Prairie", state: "TX" },
  { city: "Augusta", state: "GA" },
  { city: "Tallahassee", state: "FL" },
  { city: "Peoria", state: "AZ" },
  { city: "Cape Coral", state: "FL" },
  { city: "Charleston", state: "SC" },
  { city: "Little Rock", state: "AR" },
  { city: "New Haven", state: "CT" },
  { city: "Columbia", state: "SC" },
  { city: "Savannah", state: "GA" },
  { city: "Hartford", state: "CT" },
  { city: "Bridgeport", state: "CT" },
  { city: "Allentown", state: "PA" },
  { city: "Manchester", state: "NH" },
  { city: "Wilmington", state: "DE" },
  { city: "Burlington", state: "VT" },
  { city: "Fargo", state: "ND" },
  { city: "Bismarck", state: "ND" },
  { city: "Cheyenne", state: "WY" },
  { city: "Billings", state: "MT" },
  { city: "Missoula", state: "MT" },
  { city: "Helena", state: "MT" },
  { city: "Eugene", state: "OR" },
  { city: "Salem", state: "OR" },
  { city: "Olympia", state: "WA" },
  { city: "Juneau", state: "AK" },
  { city: "Dover", state: "DE" },
  { city: "Annapolis", state: "MD" },
  { city: "Montpelier", state: "VT" },
  { city: "Concord", state: "NH" },
  { city: "Augusta", state: "ME" },
  { city: "Portland", state: "ME" },
  { city: "Springfield", state: "IL" },
  { city: "Springfield", state: "MA" },
  { city: "Springfield", state: "MO" },
  { city: "Columbus", state: "GA" },
  { city: "Macon", state: "GA" },
  { city: "Montgomery", state: "AL" },
  { city: "Mobile", state: "AL" },
  { city: "Shreveport", state: "LA" },
  { city: "Jackson", state: "MS" },
  { city: "Gulfport", state: "MS" },
  { city: "Topeka", state: "KS" },
  { city: "Lincoln", state: "NE" },
  { city: "Billings", state: "MT" },
  { city: "Pittsburg", state: "KS" },
  { city: "Wichita Falls", state: "TX" },
  { city: "Odessa", state: "TX" },
  { city: "Midland", state: "TX" },
  { city: "Abilene", state: "TX" },
  { city: "Beaumont", state: "TX" },
  { city: "Tyler", state: "TX" },
  { city: "Longview", state: "TX" },
  { city: "Waco", state: "TX" },
  { city: "Killeen", state: "TX" },
  { city: "Temple", state: "TX" },
  { city: "Round Rock", state: "TX" },
  { city: "San Marcos", state: "TX" },
  { city: "New Braunfels", state: "TX" },
  { city: "Georgetown", state: "TX" },
  { city: "Pflugerville", state: "TX" },
  { city: "Cedar Park", state: "TX" },
  { city: "League City", state: "TX" },
  { city: "Sugar Land", state: "TX" },
  { city: "Baytown", state: "TX" },
  { city: "Pasadena", state: "CA" },
  { city: "Torrance", state: "CA" },
  { city: "Garden Grove", state: "CA" },
  { city: "Riverside", state: "CA" },
  { city: "San Bernardino", state: "CA" },
  { city: "Ontario", state: "CA" },
  { city: "Rancho Cucamonga", state: "CA" },
  { city: "Corona", state: "CA" },
  { city: "Escondido", state: "CA" },
  { city: "Elk Grove", state: "CA" },
  { city: "Roseville", state: "CA" },
  { city: "Chula Vista", state: "CA" },
  { city: "Hayward", state: "CA" },
  { city: "Pomona", state: "CA" },
  { city: "Sunnyvale", state: "CA" },
  { city: "Visalia", state: "CA" },
  { city: "Salinas", state: "CA" },
  { city: "Santa Rosa", state: "CA" },
  { city: "Concord", state: "CA" },
  { city: "Fullerton", state: "CA" },
  { city: "Victorville", state: "CA" },
  { city: "Simi Valley", state: "CA" },
  { city: "Lancaster", state: "CA" },
  { city: "Palmdale", state: "CA" },
  { city: "El Monte", state: "CA" },
  { city: "Inglewood", state: "CA" },
  { city: "Downey", state: "CA" },
  { city: "Norwalk", state: "CA" },
  { city: "Burbank", state: "CA" },
  { city: "Newport Beach", state: "CA" },
  { city: "Santa Barbara", state: "CA" },
  { city: "Santa Cruz", state: "CA" },
  { city: "Monterey", state: "CA" },
  { city: "Berkeley", state: "CA" },
  { city: "Palo Alto", state: "CA" },
  { city: "Redwood City", state: "CA" },
  { city: "Mountain View", state: "CA" },
  { city: "Santa Clara", state: "CA" },
  { city: "Cupertino", state: "CA" },
  { city: "Bellevue", state: "WA" },
  { city: "Redmond", state: "WA" },
  { city: "Everett", state: "WA" },
  { city: "Kent", state: "WA" },
  { city: "Renton", state: "WA" },
  { city: "Vancouver", state: "WA" },
  { city: "Bellingham", state: "WA" },
  { city: "Fort Collins", state: "CO" },
  { city: "Boulder", state: "CO" },
  { city: "Greeley", state: "CO" },
  { city: "Pueblo", state: "CO" },
  { city: "Grand Junction", state: "CO" },
  { city: "Loveland", state: "CO" },
  { city: "Flagstaff", state: "AZ" },
  { city: "Tempe", state: "AZ" },
  { city: "Peoria", state: "AZ" },
  { city: "Surprise", state: "AZ" },
  { city: "Prescott", state: "AZ" },
  { city: "Flagstaff", state: "AZ" },
  { city: "Yuma", state: "AZ" },
  { city: "Fort Lauderdale", state: "FL" },
  { city: "Hollywood", state: "FL" },
  { city: "Gainesville", state: "FL" },
  { city: "Palm Bay", state: "FL" },
  { city: "Pompano Beach", state: "FL" },
  { city: "West Palm Beach", state: "FL" },
  { city: "Clearwater", state: "FL" },
  { city: "Palm Coast", state: "FL" },
  { city: "Lakeland", state: "FL" },
  { city: "Miramar", state: "FL" },
  { city: "Deltona", state: "FL" },
  { city: "Naples", state: "FL" },
  { city: "Sarasota", state: "FL" },
  { city: "Melbourne", state: "FL" },
  { city: "Jacksonville Beach", state: "FL" },
  { city: "Key West", state: "FL" },
  { city: "Asheville", state: "NC" },
  { city: "Wilmington", state: "NC" },
  { city: "Charlotte", state: "NC" },
  { city: "Cary", state: "NC" },
  { city: "Gastonia", state: "NC" },
  { city: "High Point", state: "NC" },
  { city: "Greenville", state: "NC" },
  { city: "Roanoke", state: "VA" },
  { city: "Alexandria", state: "VA" },
  { city: "Hampton", state: "VA" },
  { city: "Norfolk", state: "VA" },
  { city: "Newport News", state: "VA" },
  { city: "Portsmouth", state: "VA" },
  { city: "Suffolk", state: "VA" },
  { city: "Charlottesville", state: "VA" },
  { city: "Lynchburg", state: "VA" },
  { city: "Fredericksburg", state: "VA" },
  { city: "Chattanooga", state: "TN" },
  { city: "Clarksville", state: "TN" },
  { city: "Murfreesboro", state: "TN" },
  { city: "Franklin", state: "TN" },
  { city: "Johnson City", state: "TN" },
  { city: "Kingsport", state: "TN" },
  { city: "Bristol", state: "TN" },
  { city: "South Bend", state: "IN" },
  { city: "Evansville", state: "IN" },
  { city: "Carmel", state: "IN" },
  { city: "Bloomington", state: "IN" },
  { city: "Gary", state: "IN" },
  { city: "Toledo", state: "OH" },
  { city: "Dayton", state: "OH" },
  { city: "Canton", state: "OH" },
  { city: "Youngstown", state: "OH" },
  { city: "Elyria", state: "OH" },
  { city: "Middletown", state: "OH" },
  { city: "Kettering", state: "OH" },
  { city: "Newark", state: "OH" },
  { city: "Ann Arbor", state: "MI" },
  { city: "Flint", state: "MI" },
  { city: "Lansing", state: "MI" },
  { city: "Sterling Heights", state: "MI" },
  { city: "Dearborn", state: "MI" },
  { city: "Livonia", state: "MI" },
  { city: "Troy", state: "MI" },
  { city: "Warren", state: "MI" },
  { city: "Kalamazoo", state: "MI" },
  { city: "Grand Rapids", state: "MI" },
  { city: "Traverse City", state: "MI" },
  { city: "Green Bay", state: "WI" },
  { city: "Madison", state: "WI" },
  { city: "Eau Claire", state: "WI" },
  { city: "Appleton", state: "WI" },
  { city: "Oshkosh", state: "WI" },
  { city: "Kenosha", state: "WI" },
  { city: "Racine", state: "WI" },
  { city: "La Crosse", state: "WI" },
  { city: "St. Paul", state: "MN" },
  { city: "Rochester", state: "MN" },
  { city: "Duluth", state: "MN" },
  { city: "Bloomington", state: "MN" },
  { city: "Eden Prairie", state: "MN" },
  { city: "Maple Grove", state: "MN" },
  { city: "Davenport", state: "IA" },
  { city: "Cedar Rapids", state: "IA" },
  { city: "Iowa City", state: "IA" },
  { city: "Waterloo", state: "IA" },
  { city: "Council Bluffs", state: "IA" },
  { city: "Columbia", state: "MO" },
  { city: "Independence", state: "MO" },
  { city: "Springfield", state: "MO" },
  { city: "Joplin", state: "MO" },
  { city: "Jefferson City", state: "MO" },
  { city: "Lincoln", state: "NE" },
  { city: "Waco", state: "TX" },
  { city: "Norman", state: "OK" },
  { city: "Lawton", state: "OK" },
  { city: "Enid", state: "OK" },
  { city: "Stillwater", state: "OK" },
  { city: "Broken Arrow", state: "OK" },
  { city: "Edmond", state: "OK" },
  { city: "Olathe", state: "KS" },
  { city: "Lawrence", state: "KS" },
  { city: "Manhattan", state: "KS" },
  { city: "Salina", state: "KS" },
  { city: "Hutchinson", state: "KS" },
  { city: "Fayetteville", state: "AR" },
  { city: "Fort Smith", state: "AR" },
  { city: "Springdale", state: "AR" },
  { city: "Jonesboro", state: "AR" },
  { city: "Hot Springs", state: "AR" },
  { city: "Nashua", state: "NH" },
  { city: "Rochester", state: "NH" },
  { city: "Keene", state: "NH" },
  { city: "Bangor", state: "ME" },
  { city: "Lewiston", state: "ME" },
  { city: "South Portland", state: "ME" },
  { city: "Waterbury", state: "CT" },
  { city: "Stamford", state: "CT" },
  { city: "Norwalk", state: "CT" },
  { city: "Danbury", state: "CT" },
  { city: "New Britain", state: "CT" },
  { city: "Bristol", state: "CT" },
  { city: "New London", state: "CT" },
  { city: "Providence", state: "RI" },
  { city: "Warwick", state: "RI" },
  { city: "Cranston", state: "RI" },
  { city: "Pawtucket", state: "RI" },
  { city: "Woonsocket", state: "RI" },
  { city: "Newport", state: "RI" },
  { city: "Burlington", state: "VT" },
  { city: "South Burlington", state: "VT" },
  { city: "Rutland", state: "VT" },
  { city: "Syracuse", state: "NY" },
  { city: "Albany", state: "NY" },
  { city: "Rochester", state: "NY" },
  { city: "Ithaca", state: "NY" },
  { city: "Schenectady", state: "NY" },
  { city: "Utica", state: "NY" },
  { city: "Binghamton", state: "NY" },
  { city: "Scranton", state: "PA" },
  { city: "Harrisburg", state: "PA" },
  { city: "Reading", state: "PA" },
  { city: "Bethlehem", state: "PA" },
  { city: "Lancaster", state: "PA" },
  { city: "York", state: "PA" },
  { city: "Erie", state: "PA" },
  { city: "State College", state: "PA" },
  { city: "Wilkes-Barre", state: "PA" },
  { city: "Camden", state: "NJ" },
  { city: "Paterson", state: "NJ" },
  { city: "Elizabeth", state: "NJ" },
  { city: "Trenton", state: "NJ" },
  { city: "Edison", state: "NJ" },
  { city: "Princeton", state: "NJ" },
  { city: "Hoboken", state: "NJ" },
  { city: "New Brunswick", state: "NJ" },
  { city: "Dover", state: "NH" },
  { city: "Wilmington", state: "NC" },
  { city: "Worcester", state: "MA" },
  { city: "Springfield", state: "MA" },
  { city: "Lowell", state: "MA" },
  { city: "Cambridge", state: "MA" },
  { city: "New Bedford", state: "MA" },
  { city: "Brockton", state: "MA" },
  { city: "Quincy", state: "MA" },
  { city: "Lynn", state: "MA" },
  { city: "Fall River", state: "MA" },
  { city: "Newton", state: "MA" },
  { city: "Somerville", state: "MA" },
  { city: "Framingham", state: "MA" },
  { city: "Waltham", state: "MA" },
  { city: "Amherst", state: "MA" },
  { city: "Newark", state: "NJ" },
  { city: "Greenville", state: "SC" },
  { city: "Spartanburg", state: "SC" },
  { city: "Florence", state: "SC" },
  { city: "Myrtle Beach", state: "SC" },
  { city: "Hilton Head", state: "SC" },
  { city: "Rock Hill", state: "SC" },
  { city: "Athens", state: "GA" },
  { city: "Albany", state: "GA" },
  { city: "Warner Robins", state: "GA" },
  { city: "Valdosta", state: "GA" },
  { city: "Atlanta", state: "GA" },
  { city: "Pensacola", state: "FL" },
  { city: "Panama City", state: "FL" },
  { city: "Ocala", state: "FL" },
  { city: "Daytona Beach", state: "FL" },
  { city: "Titusville", state: "FL" },
  { city: "Homestead", state: "FL" },
  { city: "Coral Springs", state: "FL" },
  { city: "Plantation", state: "FL" },
  { city: "Boynton Beach", state: "FL" },
  { city: "Delray Beach", state: "FL" },
  { city: "Boca Raton", state: "FL" },
  { city: "Coconut Creek", state: "FL" },
  { city: "Jupiter", state: "FL" },
  { city: "Stuart", state: "FL" },
  { city: "Port St. Lucie", state: "FL" },
  { city: "Fort Myers", state: "FL" },
  { city: "Bonita Springs", state: "FL" },
  { city: "Estero", state: "FL" },
  { city: "Cape Coral", state: "FL" },
  { city: "Punta Gorda", state: "FL" },
  { city: "Venice", state: "FL" },
  { city: "Bradenton", state: "FL" },
  { city: "Tampa", state: "FL" },
  { city: "St. Petersburg", state: "FL" },
  { city: "Clearwater", state: "FL" },
  { city: "Dunedin", state: "FL" },
  { city: "Largo", state: "FL" },
  { city: "Pinellas Park", state: "FL" },
  { city: "New Port Richey", state: "FL" },
  { city: "Zephyrhills", state: "FL" },
  { city: "Dade City", state: "FL" },
  { city: "Lakeland", state: "FL" },
  { city: "Winter Haven", state: "FL" },
  { city: "Sebring", state: "FL" },
  { city: "Bartow", state: "FL" },
  { city: "Lakeland", state: "FL" },
  { city: "Haines City", state: "FL" },
  { city: "Kissimmee", state: "FL" },
  { city: "Sanford", state: "FL" },
  { city: "Altamonte Springs", state: "FL" },
  { city: "Winter Park", state: "FL" },
  { city: "Maitland", state: "FL" },
  { city: "Apopka", state: "FL" },
  { city: "Oviedo", state: "FL" },
  { city: "Lake Mary", state: "FL" },
  { city: "Deland", state: "FL" },
  { city: "Daytona Beach", state: "FL" },
  { city: "Flagler Beach", state: "FL" },
  { city: "Palm Coast", state: "FL" },
  { city: "St. Augustine", state: "FL" },
  { city: "Fernandina Beach", state: "FL" },
  { city: "Miami", state: "FL" },
  { city: "Miami Beach", state: "FL" },
  { city: "Miami Gardens", state: "FL" },
  { city: "North Miami", state: "FL" },
  { city: "North Miami Beach", state: "FL" },
  { city: "Aventura", state: "FL" },
  { city: "Sunny Isles Beach", state: "FL" },
  { city: "Doral", state: "FL" },
  { city: "Hialeah", state: "FL" },
  { city: "Hialeah Gardens", state: "FL" },
  { city: "Medley", state: "FL" },
  { city: "Miami Springs", state: "FL" },
  { city: "Key Biscayne", state: "FL" },
  { city: "Coral Gables", state: "FL" },
  { city: "South Miami", state: "FL" },
  { city: "Homestead", state: "FL" },
  { city: "Florida City", state: "FL" },
  { city: "Cutler Bay", state: "FL" },
  { city: "Palmetto Bay", state: "FL" },
  { city: "Pinecrest", state: "FL" },
  { city: "San Antonio", state: "TX" },
  { city: "Schertz", state: "TX" },
  { city: "Cibolo", state: "TX" },
  { city: "Seguin", state: "TX" },
  { city: "Kerrville", state: "TX" },
  { city: "Boerne", state: "TX" },
  { city: "Fredericksburg", state: "TX" },
  { city: "Buda", state: "TX" },
  { city: "Kyle", state: "TX" },
  { city: "Bastrop", state: "TX" },
  { city: "Elgin", state: "TX" },
  { city: "Lockhart", state: "TX" },
  { city: "La Grange", state: "TX" },
  { city: "Brenham", state: "TX" },
  { city: "Navasota", state: "TX" },
  { city: "Huntsville", state: "TX" },
  { city: "Conroe", state: "TX" },
  { city: "The Woodlands", state: "TX" },
  { city: "Tomball", state: "TX" },
  { city: "Katy", state: "TX" },
  { city: "Cypress", state: "TX" },
  { city: "Richmond", state: "TX" },
  { city: "Rosenberg", state: "TX" },
  { city: "Fulshear", state: "TX" },
  { city: "Missouri City", state: "TX" },
  { city: "Stafford", state: "TX" },
  { city: "Pearland", state: "TX" },
  { city: "Friendswood", state: "TX" },
  { city: "Webster", state: "TX" },
  { city: "Clear Lake Shores", state: "TX" },
  { city: "Kemah", state: "TX" },
  { city: "Seabrook", state: "TX" },
  { city: "La Porte", state: "TX" },
  { city: "Deer Park", state: "TX" },
  { city: "Channelview", state: "TX" },
  { city: "Pasadena", state: "TX" },
  { city: "South Houston", state: "TX" },
  { city: "Galena Park", state: "TX" },
  { city: "Jacinto City", state: "TX" },
  { city: "Houston", state: "TX" },
  { city: "Bellaire", state: "TX" },
  { city: "West University Place", state: "TX" },
  { city: "River Oaks", state: "TX" },
  { city: "Humble", state: "TX" },
  { city: "Kingwood", state: "TX" },
  { city: "Atascocita", state: "TX" },
  { city: "Spring", state: "TX" },
  { city: "Huntsville", state: "AL" },
  { city: "Decatur", state: "AL" },
  { city: "Florence", state: "AL" },
  { city: "Gadsden", state: "AL" },
  { city: "Auburn", state: "AL" },
  { city: "Opelika", state: "AL" },
  { city: "Dothan", state: "AL" },
  { city: "Enterprise", state: "AL" },
  { city: "Tuscaloosa", state: "AL" },
  { city: "Hoover", state: "AL" },
  { city: "Vestavia Hills", state: "AL" },
  { city: "Homewood", state: "AL" },
  { city: "Mountain Brook", state: "AL" },
  { city: "Trussville", state: "AL" },
  { city: "Pelham", state: "AL" },
  { city: "Alabaster", state: "AL" },
  { city: "Bessemer", state: "AL" },
  { city: "Fairfield", state: "AL" },
  { city: "Leeds", state: "AL" },
  { city: "Hueytown", state: "AL" },
  { city: "Tarrant", state: "AL" },
  { city: "Gardendale", state: "AL" },
  { city: "Fultondale", state: "AL" },
  { city: "Clay", state: "AL" },
  { city: "Pinson", state: "AL" },
  { city: "Center Point", state: "AL" },
  { city: "Irondale", state: "AL" },
  { city: "Leeds", state: "AL" },
  { city: "Oxford", state: "AL" },
  { city: "Anniston", state: "AL" },
  { city: "Phenix City", state: "AL" },
  { city: "Columbus", state: "GA" },
  { city: "Columbus", state: "OH" },
  { city: "Columbus", state: "IN" },
  { city: "Columbia", state: "SC" },
  { city: "Columbia", state: "MO" },
  { city: "Columbia", state: "TN" },
  { city: "Columbia", state: "MD" },
  { city: "Columbia", state: "PA" },
  { city: "Springfield", state: "IL" },
  { city: "Springfield", state: "MA" },
  { city: "Springfield", state: "MO" },
  { city: "Springfield", state: "OH" },
  { city: "Springfield", state: "OR" },
  { city: "Springfield", state: "VA" },
  { city: "Springfield", state: "NJ" },
  { city: "Springfield", state: "TN" },
  { city: "Georgetown", state: "TX" },
  { city: "Georgetown", state: "SC" },
  { city: "Georgetown", state: "KY" },
  { city: "Georgetown", state: "DE" },
  { city: "Georgetown", state: "Guyana" },
  { city: "Charleston", state: "SC" },
  { city: "Charleston", state: "WV" },
  { city: "Charleston", state: "IL" },
  { city: "Franklin", state: "TN" },
  { city: "Franklin", state: "MA" },
  { city: "Franklin", state: "WI" },
  { city: "Franklin", state: "IN" },
  { city: "Franklin", state: "KY" },
  { city: "Portland", state: "OR" },
  { city: "Portland", state: "ME" },
  { city: "Portland", state: "TX" },
  { city: "Portland", state: "TN" },
  { city: "Portland", state: "MI" },
  { city: "Portland", state: "IN" },
  { city: "Manchester", state: "NH" },
  { city: "Manchester", state: "CT" },
  { city: "Manchester", state: "VT" },
  { city: "Manchester", state: "TN" },
  { city: "Manchester", state: "IA" },
  { city: "Lancaster", state: "PA" },
  { city: "Lancaster", state: "CA" },
  { city: "Lancaster", state: "OH" },
  { city: "Lancaster", state: "SC" },
  { city: "Lancaster", state: "TX" },
  { city: "Pittsburgh", state: "PA" },
  { city: "Pittsburg", state: "CA" },
  { city: "Pittsburg", state: "KS" },
  { city: "Rochester", state: "NY" },
  { city: "Rochester", state: "MN" },
  { city: "Rochester", state: "MI" },
  { city: "Rochester", state: "NH" },
  { city: "Rochester", state: "VT" },
  { city: "Madison", state: "WI" },
  { city: "Madison", state: "AL" },
  { city: "Madison", state: "MS" },
  { city: "Madison", state: "NJ" },
  { city: "Madison", state: "CT" },
  { city: "Madison", state: "TN" },
  { city: "Lexington", state: "KY" },
  { city: "Lexington", state: "MA" },
  { city: "Lexington", state: "SC" },
  { city: "Lexington", state: "NC" },
  { city: "Lexington", state: "VA" },
  { city: "Auburn", state: "AL" },
  { city: "Auburn", state: "ME" },
  { city: "Auburn", state: "NY" },
  { city: "Auburn", state: "WA" },
  { city: "Auburn", state: "CA" },
  { city: "Macon", state: "GA" },
  { city: "Macon", state: "MS" },
  { city: "Macon", state: "MO" },
  { city: "Burlington", state: "VT" },
  { city: "Burlington", state: "NC" },
  { city: "Burlington", state: "IA" },
  { city: "Burlington", state: "MA" },
  { city: "Burlington", state: "NJ" },
  { city: "Burlington", state: "WA" },
  { city: "Burlington", state: "WI" },
  { city: "Burlington", state: "KY" },
  { city: "Burlington", state: "CO" },
  { city: "Burlington", state: "VT" },
  { city: "Salem", state: "OR" },
  { city: "Salem", state: "MA" },
  { city: "Salem", state: "NH" },
  { city: "Salem", state: "VA" },
  { city: "Salem", state: "NC" },
  { city: "Salem", state: "NJ" },
  { city: "Salem", state: "OH" },
  { city: "Salem", state: "IL" },
  { city: "Hampton", state: "VA" },
  { city: "Hampton", state: "NH" },
  { city: "Hampton", state: "GA" },
  { city: "Hampton", state: "IA" },
  { city: "Raleigh", state: "NC" },
  { city: "Raleigh", state: "MS" },
  { city: "Raleigh", state: "ND" },
  { city: "Albany", state: "NY" },
  { city: "Albany", state: "OR" },
  { city: "Albany", state: "GA" },
  { city: "Albany", state: "CA" },
  { city: "Albany", state: "VT" },
  { city: "Albany", state: "TX" },
  { city: "Augusta", state: "GA" },
  { city: "Augusta", state: "ME" },
  { city: "Augusta", state: "KS" },
  { city: "Augusta", state: "AR" },
  { city: "Augusta", state: "WI" },
  { city: "Greenville", state: "SC" },
  { city: "Greenville", state: "NC" },
  { city: "Greenville", state: "MS" },
  { city: "Greenville", state: "TX" },
  { city: "Greenville", state: "OH" },
  { city: "Greenville", state: "MI" },
  { city: "Greenville", state: "IL" },
  { city: "Charleston", state: "SC" },
  { city: "Charleston", state: "WV" },
  { city: "Charleston", state: "IL" },
  { city: "Charleston", state: "AR" },
  { city: "Charleston", state: "MO" },
  { city: "Charleston", state: "MS" },
  { city: "Charleston", state: "TN" },
  { city: "Charleston", state: "TX" },
  { city: "Charleston", state: "VA" },
]