module RagQueryStubs
  def stub_rag_components
    fake_chunks = [
      instance_double(Ai::DocumentChunk, content: "Adoption fee is $200.", id: 1),
      instance_double(Ai::DocumentChunk, content: "We require a home visit.", id: 2),
      instance_double(Ai::DocumentChunk, content: "Application processing takes 3-5 days.", id: 3)
    ]

    allow(Ai::Rag::EmbeddingService).to receive(:call).and_return(Array.new(1536) { 0.1 })
    allow(Ai::Rag::VectorSearch).to receive(:call).and_return(fake_chunks)
    allow(Ai::Rag::QueryEngine).to receive(:call).and_return("This is a test answer generated by AI.")
  end

  def unstub_rag_components
    allow(Ai::Rag::EmbeddingService).to receive(:call).and_call_original
    allow(Ai::Rag::VectorSearch).to receive(:call).and_call_original
    allow(Ai::Rag::QueryEngine).to receive(:call).and_call_original
  end
end

RSpec.configure do |config|
  config.include RagQueryStubs
end
