default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "tovitu" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "tovitu_dev" } %>

development:
  <<: *default
  database: tovitu_development

test:
  <<: *default
  database: tovitu_test

production:
  primary: &primary_production
    <<: *default
    database: tovitu_production
    username: <%= ENV["TOVITU_DATABASE_USER"] %>
    password: <%= ENV["TOVITU_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: tovitu_production_cache
    migrations_paths: db/cache_migrate
  cable:
    <<: *primary_production
    database: tovitu_production_cable
    migrations_paths: db/cable_migrate
