development:
  :url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/0" } %>
  :concurrency: 5

test:
  :url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/0" } %>
  :concurrency: 5

production:
  :url: <%= ENV["REDIS_URL"] %>
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 10 } %>
  :queues:
    - [default, 1]
    - [mailers, 2]
