require "rails_helper"

RSpec.describe "Ai::RagQueries" do
  let(:shelter) { create(:shelter, :with_admin) }
  let(:pet) do
    create(:pet, shelter: shelter, name: "Buddy", species: "dog", breed: "Labrador",
                 age_category: "adult", sex: "male", status: "available")
  end
  let(:application) do
    create(:adoption_application, pet: pet, shelter: shelter,
                                  status: "pending",
                                  token: "test-token-123",
                                  applicant_name: "John Doe",
                                  applicant_email: "john@example.com")
  end

  before do
    stub_rag_components
  end

  after { unstub_rag_components }

  describe "POST /shelters/:shelter_id/rag_queries" do
    it "returns 200 with answer for a valid question" do
      post shelter_rag_queries_path(shelter_id: shelter), params: { question: "What is your adoption fee?" }

      expect(response).to have_http_status(:ok)
      json = response.parsed_body
      expect(json["answer"]).to eq("This is a test answer generated by AI.")
    end

    it "returns 422 for blank question" do
      post shelter_rag_queries_path(shelter_id: shelter), params: { question: "" }

      expect(response).to have_http_status(:unprocessable_entity)
      json = response.parsed_body
      expect(json["error"]).to eq(I18n.t("ai.rag.question_required"))
    end

    it "returns 404 for non-existent shelter" do
      post shelter_rag_queries_path(shelter_id: 0), params: { question: "What is your adoption fee?" }

      expect(response).to have_http_status(:not_found)
    end

    it "is publicly accessible (no auth required)" do
      post shelter_rag_queries_path(shelter_id: shelter), params: { question: "Test?" }

      expect(response).to have_http_status(:ok)
    end

    it "returns 404 for discarded shelters" do
      discarded_shelter = create(:shelter, :discarded)
      post shelter_rag_queries_path(shelter_id: discarded_shelter), params: { question: "Test?" }

      expect(response).to have_http_status(:not_found)
    end

    context "caching", :cache do
      around do |example|
        old_cache = Rails.cache
        Rails.cache = ActiveSupport::Cache::MemoryStore.new
        example.run
      ensure
        Rails.cache = old_cache
      end

      it "caches identical question+shelter combination" do
        expect(Ai::Rag::EmbeddingService).to receive(:call).once.and_return(Array.new(1536) { 0.1 })
        expect(Ai::Rag::VectorSearch).to receive(:call).once.and_return([])
        expect(Ai::Rag::QueryEngine).to receive(:call).once.and_return("Answer")

        2.times do
          post shelter_rag_queries_path(shelter_id: shelter),
               params: { question: "What is your adoption fee?" }
        end

        expect(response).to have_http_status(:ok)
      end

      it "does not share cache between different questions" do
        expect(Ai::Rag::EmbeddingService).to receive(:call).twice.and_return(Array.new(1536) { 0.1 })
        expect(Ai::Rag::VectorSearch).to receive(:call).twice.and_return([])
        expect(Ai::Rag::QueryEngine).to receive(:call).twice.and_return("Answer")

        post shelter_rag_queries_path(shelter_id: shelter),
             params: { question: "Question one?" }
        post shelter_rag_queries_path(shelter_id: shelter),
             params: { question: "Question two?" }
      end
    end
  end

  describe "POST /adoption_applications/:token/rag_queries" do
    it "returns 200 with answer for a valid question" do
      post adoption_application_rag_queries_path(adoption_application_id: application.token),
           params: { question: "What is the status of my application?" }

      expect(response).to have_http_status(:ok)
      json = response.parsed_body
      expect(json["answer"]).to eq("This is a test answer generated by AI.")
    end

    it "returns 422 for blank question" do
      post adoption_application_rag_queries_path(adoption_application_id: application.token),
           params: { question: "" }

      expect(response).to have_http_status(:unprocessable_entity)
      json = response.parsed_body
      expect(json["error"]).to eq(I18n.t("ai.rag.question_required"))
    end

    it "returns 404 for non-existent token" do
      post adoption_application_rag_queries_path(adoption_application_id: "nonexistent-token"),
           params: { question: "Test?" }

      expect(response).to have_http_status(:not_found)
    end

    context "with timeline events" do
      before do
        create(:adoption_timeline_event, adoption_application: application,
                                          event_type: "created", created_at: 2.days.ago)
        create(:adoption_timeline_event, adoption_application: application,
                                          event_type: "info_requested", created_at: 1.day.ago)
      end

      it "includes timeline events in extra_variables" do
        expect(Ai::Rag::QueryEngine).to receive(:call).with(
          hash_including(
            extra_variables: hash_including(
              application_status: "pending",
              application_timeline: a_string_including("created")
            )
          )
        ).and_return("Timeline answer")

        post adoption_application_rag_queries_path(adoption_application_id: application.token),
             params: { question: "What's happening with my app?" }
      end
    end

    context "with notes" do
      let(:staff_user) { create(:user, :verified, :shelter_admin, shelter: shelter) }

      before do
        create(:adoption_note, adoption_application: application, user: staff_user,
                                content: "Applicant seems like a great fit.")
      end

      it "includes notes in extra_variables" do
        expect(Ai::Rag::QueryEngine).to receive(:call).with(
          hash_including(
            extra_variables: hash_including(
              application_notes: a_string_including("great fit")
            )
          )
        ).and_return("Notes answer")

        post adoption_application_rag_queries_path(adoption_application_id: application.token),
             params: { question: "Any notes on my application?" }
      end
    end
  end
end
